# Generated by Django 6.0.6 on 2026-07-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=200, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flavours/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
